from snakemake.utils import min_version

min_version("7.32.4")


configfile: "../config/config.yaml"


# Parameters
ASSEMBLY = config["GENOME"]["ASSEMBLY"]
PROVIDER = config["GENOME"]["PROVIDER"]
FILTER = config["GENOME"]["FILTER"]
OUTDIR = config["GENOME"]["OUTDIR"]


rule install_genome:
    default_target: True
    message:
        """
        Installs target genome(s) under install dir
        - Regex to filter down to main chromosomes
        - Default provider set to UCSC
        """
    output:
        OUTDIR + f"/{ASSEMBLY}/{ASSEMBLY}.fa.gz",
    params:
        assembly=ASSEMBLY,
        provider=PROVIDER,
        regex=FILTER,
        outdir=OUTDIR,
    conda:
        "envs/genome.yaml"
    threads: 8
    shell:
        """
        genomepy plugin enable blacklist &&
        genomepy install {params.assembly} \
        --provider {params.provider} \
        --genomes_dir {params.outdir} \
        --bgzip \
        --threads {threads} \
        --regex {params.regex}
        """
