GENOME:
  # Genome builds
  BUILDS:
    - hg38
    - hg19
  # Genome source
  SOURCE: UCSC
  # Regex filtering - filter FASTA to main chromosomes
  FILTER: chr[0-9XY]+$
  # Blacklist URLs
  BLACKLIST_HG19: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg19-blacklist.v2.bed.gz
  BLACKLIST_HG38: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg38-blacklist.v2.bed.gz
